# Generated by Django 5.0 on 2023-12-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Title')),
                ('view', models.CharField(max_length=200, verbose_name='Content')),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Productmodel',
        ),
    ]
